### PR TITLE
Ensure actions are not displayed on TaskRuns in ReadOnly mode

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1270

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Hey Megan, thanks for the feedback. I'm not seeing the overflow menu show up locally... Have you run `npm run bootstrap` after checkout out this PR?

**Comment by Megan-Wright** [comment]
> Hey Megan, thanks for the feedback. I'm not seeing the overflow menu show up locally... Have you run `npm run bootstrap` after checkout out this PR?

Oh yep forgot to do that - you're right actually looks completely fine!
/lgtm 
/meow hats

**Comment by a-roberts** [comment]
Hmm, seeing 

```
I0409 15:57:16.939] 2020/04/09 15:57:16 main.go:722: --gcp-project is missing, trying to fetch a project from boskos.
I0409 15:57:16.944] (for local runs please set --gcp-project to your dev project)
I0409 15:57:16.944] 2020/04/09 15:57:16 main.go:734: provider gke, will acquire project type gke-project from boskos
I0409 16:02:50.906] 2020/04/09 16:02:50 main.go:316: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resources not found
```

👀

**Comment by AlanGreene** [comment]
OK looking at Prow we seem to be through the backlog of builds now, trying this one again.

/test pull-tekton-dashboard-integration-tests

**Pull request merged**
