### PR TITLE
Introduce Kustomize and create locked-down dashboard build

### PR DESCRIPTION
**Pull request by mnuttall**
# Changes

For https://github.com/tektoncd/dashboard/issues/839

Use Kustomize to general config yaml for eight scenarios:
(local build or latest from gcr) * (plain kube or OpenShift) * (locked down or full featured rbac)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by mnuttall** [comment]
All tests passed - but I need to squash my commits.

**Comment by mnuttall** [comment]
Thanks @a-roberts ! Fixes squashed and pushed.

**Comment by mnuttall** [comment]
I'm hitting https://github.com/tektoncd/dashboard/issues/902 repeatedly
/retest

**Comment by mnuttall** [comment]
full and read-only versions now confirmed working on OpenShift. Ready for final review.

**Comment by a-roberts** [comment]
Yeah, I've had a good look at this on Mark's cluster and did testing previously so we think we've addressed everything here (else follow-ups), this is an excellent start for our read-only dashboard story that folks have been requesting

/lgtm
/approve

Follow-on work:
- https://github.com/tektoncd/dashboard/issues/951
- https://github.com/tektoncd/dashboard/issues/950

**Pull request merged**
