### PR TITLE
Update Triggers API group to match Triggers 0.4 release

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1193

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
@AlanGreene one other point to mention, I've been using this on OpenShift so we get to see any RBAC problems - we'll need to make the changes there too (so should be as simple case of using the different apigroup only again, happy to be a testing guinea pig if you can't get an environment quickly)

**Comment by AlanGreene** [comment]
Tested on CodeReady Containers locally and noticed we were missing ClusterTriggerBindings in our RBAC so added that. If you have ready access to a more production-like OpenShift environment it'd be great if you could verify it there too.

**Comment by a-roberts** [comment]
> Tested on CodeReady Containers locally and noticed we were missing ClusterTriggerBindings in our RBAC so added that. If you have ready access to a more production-like OpenShift environment it'd be great if you could verify it there too.

Thanks, yep now works perfectly (so using OpenShift 4.3, applied your two changed yaml files and no more `Forbidden` errors) 👍

**Comment by AlanGreene** [comment]
@a-roberts are we ok to get this in or holding off for something else before we switch to Triggers 0.4 support?

**Comment by a-roberts** [comment]
> @a-roberts are we ok to get this in or holding off for something else before we switch to Triggers 0.4 support?

All good, thanks
/lgtm
/approve
/meow hats

**Pull request merged**
