### PR TITLE
Don't patch service on openshift but create a secure one for the Route

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR changes the way services are managed on openshift.

Previously, we patched the original service to remove port 9097 and add port 443, this service was then used by the `Route`, then we created a second service with port 9097 to use inside the cluster.

This PR doesn't change the original service anymore, therefore it is to be used inside the cluster, instead it creates the secure service and use it in the `Route`.

This is simpler as it doesn't require modifying an existing resource, it leaves the original service as it is and creates two new resources that are openshift specific.

This should be ok with webhooks-extension as the service is looked up by labels (see https://github.com/tektoncd/experimental/pull/551).

/cc @a-roberts 
/cc @AlanGreene 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by eddycharly** [comment]
This should be ok with webhooks-extension as the service is looked up by labels (see https://github.com/tektoncd/experimental/pull/551).

**Comment by eddycharly** [comment]
ping @a-roberts

**Review by AlanGreene — APPROVED** [review]
/lgtm

**Pull request merged**
