### PR TITLE
Set content-type header only on valid request methods

### PR DESCRIPTION
**Pull request by triantium**
Avoid sending an empty Header on requests, that should not have a body.
Resolves https://github.com/tektoncd/dashboard/issues/2242

compare with https://developer.mozilla.org/de/docs/Web/HTTP/Methods
which method should and may have a body.

# Changes

Avoid sending an empty Header on requests, that should not have a body.
https://github.com/tektoncd/dashboard/issues/2242

compare with https://developer.mozilla.org/de/docs/Web/HTTP/Methods
which method should and may have a body.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by AlanGreene — CHANGES_REQUESTED** [review]
Thanks for the PR @triantium. This must also support setting the Content-Type header on PATCH requests which are used for cancelling a TaskRun/PipelineRun or starting a PipelineRun that was created in pending state.

**Comment by triantium** [comment]
Missed the Patch method.

**Review by AlanGreene — APPROVED** [review]
/lgtm
/meow

**Pull request merged**
