### PR TITLE
Update DataTableSkeleton to support `size` prop

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Update DataTableSkeleton to support a `size` prop with the same
values supported by the Carbon `Table` component, and update our
`Table` wrapper component to pass the value through.

Add control for the supported size values to the storybook.

This will be used on the updated About page loading state as part
of the react-query migration.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by LyndseyBu** [comment]
looks good, only noticed one thing with the sizes, they seem to be removing the previous terms (compact, short....) in the next major release...

image

**Comment by AlanGreene** [comment]
Thanks @LyndseyBu, I'll remove those so we don't start using them. A Carbon 11 prerelease should be available for testing in the next few weeks but I don't expect it to GA for a while yet.

**Pull request merged**
