### PR TITLE
Fix API root for token

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1373

Add the missing API root on the call to get token.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
Yep, tested this one on the release stream (0.6.1.2, which is 0.6.1.1 plus a few other cherry-picks) and things were fine there, identical code here

/lgtm
/approve

**Comment by AlanGreene** [comment]
Amended to kick off the CLA check again... and it's passed before I even comment 😆

**Pull request merged**
