### PR TITLE
Support yaml format in req/resp

### PR DESCRIPTION
**Pull request by MartinForReal**
Signed-off-by: Fan Shang Xiang <fanshangxiang@gmail.com>

# Changes

support yaml format in req/resp

# Submitter Checklist

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by AlanGreene** [comment]
@MartinForReal thanks for the PR. Is there an issue describing this change somewhere? Can you provide some detail / background here to help us understand the need for this change?

**Comment by MartinForReal** [comment]
@googlebot I signed it!

**Comment by MartinForReal** [comment]
@AlanGreene I found that the Kubernetes API server has support for YAML format. And we need to query manifest file and convert it to YAML.  So why don't we add support for producing YAML format instead?

**Comment by AlanGreene** [comment]
The dashboard processes all data in JSON format (or JSON patch for some operations on secrets/service accounts) , can you provide some examples of where you think it would benefit from requesting data in YAML format instead?

> we need to query manifest file and convert it to YAML

Can you elaborate on this? Are there specific resources and uses you have in mind?

**Comment by MartinForReal** [comment]
such as /namespaces/{namespace}/pipelines/{pipelinename}

**Comment by AlanGreene** [comment]
Are you referring to the pages in the dashboard that display the Pipeline and Task definitions?
For example:
image

If so then I don't think that requesting this data in YAML format is necessary. Converting from JSON to YAML is a simple and inexpensive operation, and it ensures that we only have a single source of truth for our data in the application.

We use data from these definitions in a number of places in the dashboard, so having a single source of truth (the JSON data we retrieve and store) helps to ensure all elements of the UI related to that resource are consistent. We're also beginning to integrate this type of YAML display in other contexts so it will be even more important that the content is consistent with other data displayed on the page for that same resource.

**Comment by AlanGreene** [comment]
Closing this now and we can revisit if we find a use case for requesting YAML directly.

**Pull request closed without merging**
