### PR TITLE
Update tests to latest Pipelines release

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by AlanGreene** [comment]
Blocked by https://github.com/tektoncd/plumbing/pull/1562

**Review by briangleeson — APPROVED** [review]
/lgtm

**Comment by AlanGreene** [comment]
PR to update prow config to use k8s 1.25 is merged but only syncs hourly, at ~12 minutes past the hour by the looks of things. I'll re-run the tests after the next sync and they should pass 🤞

**Comment by AlanGreene** [comment]
Also needed https://github.com/tektoncd/plumbing/pull/1563, which is merged and updated on prow now 🤞 
/test pull-tekton-dashboard-integration-tests

**Pull request merged**
