### PR TITLE
Split APIs by kind

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

`src/api/index.js` has become too big and APIs are in no particular
order, making it very difficult to work with.

Split the APIs into files per kind so they are easier to work with.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
@eddycharly there's a Cloudflare outage affecting a large chunk of the internet at the moment, including the nodejs site

**Comment by eddycharly** [comment]
Ah ok, error didn’t make sense that’s why I reran the tests.

**Comment by AlanGreene** [comment]
Looks like things may have recovered... 🤞 

/retest

**Comment by eddycharly** [comment]
Thank you so much for this one !
/lgtm
/approve

**Pull request merged**
