### PR TITLE
Add some Chinese translation

### PR DESCRIPTION
**Pull request by kid0809**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Thanks for the PR @kid0809. Can you sign the CLA please?

/ok-to-test

**Comment by kid0809** [comment]
> Thanks for the PR @kid0809. Can you sign the CLA please?
> 
> /ok-to-test

CLA signed

**Comment by AlanGreene** [comment]
@kid0809 it looks like the EasyCLA bot still isn't happy. https://github.com/tektoncd/dashboard/pull/2215#issuecomment-930784983

The message suggests that the email address in your commit doesn't match the email address you used to sign the CLA, or that email is not in your GitHub account email settings. Please check the instructions in that message and let me know if you have any questions.

**Comment by kid0809** [comment]
I re-signed with the correct email

**Comment by AlanGreene** [comment]
@kid0809 do you still want to contribute this change?  Reopening to check the CLA status but marking as on hold until you confirm.

/reopen
/hold

**Review by AlanGreene — APPROVED** [review]
Thanks again for the PR @kid0809 😸 

/lgtm
/hold cancel

**Pull request merged**
