### PR TITLE
Delete unused back end APIs

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/290
Delete back end code for unused dashboard APIs now that the majority of front end APIs have been migrated.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibbles** [comment]
I think delivering this will currently break the webhooks extension ...... it looks like https://github.com/tektoncd/experimental/blob/master/webhooks-extension/src/api/index.js uses the dashboard endpoints to populate namespaces, pipelines and service accounts:

```
export function getNamespaces() {
  const uri = `${dashboardAPIRoot}/namespaces`;
  return get(uri);
}

export function getPipelines(namespace) {
  const uri = `${dashboardAPIRoot}/namespaces/${namespace}/pipelines`;
  return get(uri);
}

export function getServiceAccounts(namespace) {
  const uri = `${dashboardAPIRoot}/namespaces/${namespace}/serviceaccounts`;
  return get(uri);
}
```

That code needs fixing prior to delivering this @AlanGreene @mnuttall

**Comment by AlanGreene** [comment]
@dibbles thanks for the feedback, I've opened https://github.com/tektoncd/experimental/pull/133 to update the extension

**Comment by a-roberts** [comment]
I've approve and lgtmed the extension changes: I created a webhook fine with all of Alan's changes there. Testing the two together now then good to go

**Comment by a-roberts** [comment]
Tested this works with the latest extension too, all good, just the docs then once it's off hold I'll lgtm

**Comment by AlanGreene** [comment]
Updated dev docs to remove reference to these APIs, should be good to go once the builds finish.

/hold cancel

**Comment by a-roberts** [comment]
Great, thanks Alan - I'll optimistically...

/lgtm
/approve

**Pull request merged**
