### PR TITLE
Remove dynamic import ponyfill

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/124

Dynamic import is now supported across the 4 major browsers so the ponyfill is no longer required.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
https://caniuse.com/#feat=es6-module-dynamic-import
image

**Comment by AlanGreene** [comment]
Updated version of table above showing current browser versions:
image

Release dates for the earliest versions of the four main browsers supporting dynamic import:

| Browser | Version | Release Date |
|---|---|---|
| Edge | 79 | 2020-01-15 |
| Firefox | 67 | 2019-05-21 |
| Chrome | 63 | 2017-12-06 |
| Safari | 11.1 | 2018-03-29 |

The Dashboard has some known issues with older Safari and Firefox versions going back that far, so we should recommend newer releases. We could add some sort of browser support statement in the README / install instructions. Something along the lines of:

> ### Supported browsers
> 
> The Dashboard has been tested on modern evergreen browsers, and generally supports the current and previous stable versions of:
>
> - Google Chrome (Windows, macOS, Linux)
> - Mozilla Firefox (Windows, macOS, Linux)
> - Apple Safari (macOS)
> - Microsoft Edge (Windows)
> 
> Older versions or other browsers may work, but some features may be missing or not function as expected.

**Comment by a-roberts** [comment]
> Updated version of table above showing current browser versions:
> image
> 
> Release dates for the earliest versions of the four main browsers supporting dynamic import:
> 
> Browser	Version	Release Date
> Edge	79	2020-01-15
> Firefox	67	2019-05-21
> Chrome	63	2017-12-06
> Safari	11.1	2018-03-29
> The Dashboard has some known issues with older Safari and Firefox versions going back that far, so we should recommend newer releases. We could add some sort of browser support statement in the README / install instructions. Something along the lines of:
> 
> > ### Supported browsers
> > The Dashboard has been tested on modern evergreen browsers, and generally supports the current and previous stable versions of:
> > 
> > * Google Chrome (Windows, macOS, Linux)
> > * Mozilla Firefox (Windows, macOS, Linux)
> > * Apple Safari (macOS)
> > * Microsoft Edge (Windows)
> > 
> > Older versions or other browsers may work, but some features may be missing or not function as expected.

Yeah, +1 on the supported browser section - let's add that then get this one merged?

**Comment by AlanGreene** [comment]
@a-roberts this should be good to go now, thanks

**Pull request merged**
