### PR TITLE
Refactor controllers to reduce code duplication

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR refactors the controllers implementation.

Most of the code was duplicated in the controllers.

This pull requests adds a generic controller taking care of the implementation. Dedicated controllers forward to the `Generic` controller setting the their respective arguments.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Related: https://github.com/tektoncd/dashboard/pull/1288
potential for removing use of the informers in the backend entirely

**Comment by eddycharly** [comment]
Not tested yet.

/hold

**Comment by eddycharly** [comment]
I tested it this morning, it's working fine.

/hold cancel

**Comment by eddycharly** [comment]
@AlanGreene i would say that this PR doesn't hurt while waiting for #1288 . what do you think ? if you prefer i can close it, no worries.

**Comment by AlanGreene** [comment]
I think it's still worth doing while we wait for #1288 👍 It's on my queue to review later today.

**Pull request merged**
