### PR TITLE
Update empty state strings for consistency and accuracy

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Update the strings displayed on empty tables to be more consistent
across resource types and also to be more accurate.

Since we've added label filtering support the 'no resources found'
message has been a bit misleading, it should really be 'no matching
resources found'.

This is even more obvious with the recent addition of status filtering
on the TaskRuns and PipelineRuns lists.

Update the strings used for all namespaces, cluster resources, and
selected namespace empty states.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Not sure what happened with the integration tests, logs show success...
https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_dashboard/1872/pull-tekton-dashboard-integration-tests/1338463388384104449/build-log.txt

/retest

**Review by steveodonovan — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
