### PR TITLE
Remove legacy websocket API

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Follow up to https://github.com/tektoncd/dashboard/pull/2157

Remove the code providing the legacy firehose websocket connection
based on the informers provided by the dynamic client. We have moved
the front end code to use a new model where it uses a websocket connection
per kind via the API proxy.

Also remove the generated Dashboard k8s client as it was only used for
providing websocket events for the Extensions resource via the legacy
websocket API.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Let's give https://github.com/tektoncd/dashboard/pull/2157 a few days once it's merged before we remove the backend support for the old websocket connection.

/hold

**Review by briangleeson — APPROVED** [review]
/lgtm

**Pull request merged**
