### PR TITLE
Add sha256 values to images with latest tag

### PR DESCRIPTION
**Pull request by akihikokuroda**
# Changes

In the release process, add the sha256 value to the images with the "latest" tag.  This is for the issue https://github.com/tektoncd/dashboard/issues/413

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by akihikokuroda** [comment]
I corrected the "omit".  
The failure is caused by missing the lockdown.py in the master of the repo.  It should not happen once it is in the master branch.
The release.yaml file is created in the first step in the publish task.  So the tagging must be later than the step.  I'll look into how I can stop publishing on the failure of the step.

**Comment by mnuttall** [comment]
Note to self: test this against aki's branch in his repo.

**Comment by mnuttall** [comment]
Hi @akihikokuroda I updated my `tekton-dashboard-git` resource to 
```
spec:
  params:
  - name: url
    value: https://github.com/akihikokuroda/dashboard
  - name: revision
    value: b1e1f40
  type: git
```
The build checks your code out, builds it, but still crashes out at 
```
[publish-images : tag-external-images] Installing collected packages: six, websocket-client, chardet, idna, urllib3, certifi, requests, docker
[publish-images : tag-external-images] Successfully installed certifi-2019.6.16 chardet-3.0.4 docker-4.0.2 idna-2.8 requests-2.22.0 six-1.12.0 urllib3-1.25.3 websocket-client-0.56.0
[publish-images : tag-external-images] ./lockdown.py: 1: ./lockdown.py: 404:: not found
```

I'd very much to be sure that this works before merging it. Am I still doing something wrong, or is this now showing up a problem with the script?

**Comment by akihikokuroda** [comment]
Please change the line in the publish.yaml

curl https://raw.githubusercontent.com/tektoncd/dashboard/tekton/scripts/lockdown.py --output lockdown.py 
to
curl https://raw.githubusercontent.com/akihikokuroda/dashboard/lockdown/tekton/scripts/lockdown.py --output lockdown.py

**Comment by mnuttall** [comment]
Hi Aki, 
We're making progress. Your script now runs, but I'm not sure about the shas that it generates. For example in https://console.cloud.google.com/storage/browser/_details/tekton-releases/dashboard/previous/v0.1.1-pr434-test-4/release.yaml we see, 
```
    - kubectl
    image: lachlanevenson/k8s-kubectl@sha256:18df43a4ebbdcb05dcb4fe6ea152075f3cba442c317298acd3b7c8857375ad39
    name: kubectl-apply
```
This however is not a valid image: 
```
docker pull lachlanevenson/k8s-kubectl@sha256:18df43a4ebbdcb05dcb4fe6ea152075f3cba442c317298acd3b7c8857375ad39
Error response from daemon: manifest for lachlanevenson/k8s-kubectl@sha256:18df43a4ebbdcb05dcb4fe6ea152075f3cba442c317298acd3b7c8857375ad39 not found: manifest unknown: manifest unknown
```
Checking the latest sha we see, 
```
docker pull lachlanevenson/k8s-kubectl
Using default tag: latest
latest: Pulling from lachlanevenson/k8s-kubectl
Digest: sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb
Status: Image is up to date for lachlanevenson/k8s-kubectl:latest
docker.io/lachlanevenson/k8s-kubectl:latest

docker pull lachlanevenson/k8s-kubectl@sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb
sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb: Pulling from lachlanevenson/k8s-kubectl
Digest: sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb
Status: Image is up to date for lachlanevenson/k8s-kubectl@sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb
docker.io/lachlanevenson/k8s-kubectl@sha256:c794866697bee0787ef2957a27d593146e9d78a3aa55aea66eb18efa07d4aeeb
```

Something seems wrong there. Here's the output from your task:
```
[publish-images : tag-external-images] lockdown_image
[publish-images : tag-external-images] image:lachlanevenson/k8s-kubectl:latest
[publish-images : tag-external-images] replace_image
[publish-images : tag-external-images]
[publish-images : tag-external-images] Done.
```

**Comment by akihikokuroda** [comment]
I picked up wrong the attribute from the image.  It should pick up the correct one now.  Sorry.

**Comment by mnuttall** [comment]
Great, thank you - SHAs now match. 
/approve
/lgtm

**Pull request merged**
