### PR TITLE
Address go-lint problems, readiness/health probe log message

### PR DESCRIPTION
**Pull request by a-roberts**
This should be an easy one, imported the project and noticed this in my Vscode environment with go-lint, this was bugging me and it's trivial stuff really (very basic implementation and test code changes) and we had an incorrect print for the readiness/health checks.

I've also modified the secret label to be **tektondashboard** instead of **restknative**.

For testing I ran this with a Dockerfile_test that we're going to add with a new PR coming up shortly.

Only internal field names have changed.

For convenience the test Dockerfile is as follows:

```
FROM golang:1.10 (should this be 1.12?)
USER root
RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x /usr/local/bin/dep
WORKDIR /go/src/github.com/tektoncd/dashboard/
COPY . .
#RUN dep ensure
RUN dep ensure -vendor-only
WORKDIR /go/src/github.com/tektoncd/dashboard/pkg/endpoints
RUN CGO_ENABLED=0 NAMESPACE=default GOOS=linux go test -v
```

Credits to @vtereso too for spotting the label to change too 😄

### CODE REVIEW

**Comment by mnuttall** [comment]
I merged in the Dockerfile_test to this PR and hit a test failure:
```
DeletionsRecorded not equal to 10, recorded only 9--- FAIL: TestPipelineRunWebsocket (17.00s)
    websocket_test.go:75: Enter TestPipelineRunWebsocket...
    websocket_test.go:239: DeletionsRecorded not equal to 10, recorded only 9
FAIL
exit status 1
FAIL	github.com/tektoncd/dashboard/pkg/endpoints	24.096s
The command '/bin/sh -c CGO_ENABLED=0 NAMESPACE=default GOOS=linux go test -v' returned a non-zero code: 1
```

**Comment by mnuttall** [comment]
The tests passed on a second attempt, so this looks to be timing-related.

**Comment by mnuttall** [comment]
Linting and tidy-up changes all look good.

**Comment by a-roberts** [comment]
@mnuttall RE the failing tests, I'm currently running Dockerfile_test 100 times in a loop looking for the websocket failure, @dibbles and I discussed this and I agree with his suggestion that it could be due to the counter variable not being incremented automatically. This is all test code we have (registering fake clients and tracking updates etc to them), so if that's a flaky test we should address in a different PR.

Let me know how you'd like to proceed, my code doesn't touch said code and I'd like to get this in 🤞 !

**Pull request merged**
