### PR TITLE
Replace git-init image in import resources

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

The `git-init` image is no longer published as part of the Pipelines release (it was part of the git PipelineResource support which has been removed).

Switch to `cgr.dev/chainguard/git` which provides the git client and is regularly updated for security fixes etc.

Implement the same functionality we previously had using pure git commands.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by AlanGreene** [comment]
Failed downloading Node.js tar again, hopefully not becoming a regular issue…
/test tekton-dashboard-unit-tests

**Review by briangleeson — APPROVED** [review]
/lgtm

**Pull request merged**
