### PR TITLE
Add RBAC for getting CRD info, used to detect Triggers installation

### PR DESCRIPTION
**Pull request by a-roberts**
For https://github.com/tektoncd/dashboard/issues/919

Without it we get a cryptic unknown error from the proxy and Trigger resources aren't displayed on master (including the 0.4.0 release)

Fixed about 30 linter errors too

### CODE REVIEW

**Comment by a-roberts** [comment]
@mnuttall FYI - I've resolved the yaml linter pain in this commit, be aware you'll have to pick these lovely changes up for your Kustomize work

yamllint was actually added to plumbing ages ago, it's just that we've not touched the yaml until now 😄

**Comment by AlanGreene** [comment]
So the interesting change here is adding the following to the ClusterRole:
```yaml
- apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
```

My environment mustn't have been as clean as I thought when I tested this, thanks for the fix 😸 

Looks good
/lgtm

**Comment by a-roberts** [comment]
@AlanGreene exactly, thanks for taking a look - it looks like we've still got a flaky e2e test going on (@CarolynMabbott FYI, I think you made a change recently to look for the dashboard being made up but perhaps it still needs a little work?)

**Comment by a-roberts** [comment]
```
I0120 15:46:48.839] error: error validating "STDIN": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "env" in io.k8s.api.core.v1.ResourceRequirements; if you choose to ignore these errors, turn validation off with --validate=false
```

oh, looking

**Comment by a-roberts** [comment]
Hit the other flaky now, what a time to be alive (TestExtension this time)

/test tekton-dashboard-unit-tests

**Pull request merged**
