### PR TITLE
Add some Simplified Chinese translation

### PR DESCRIPTION
**Pull request by kid0809**
# Changes

Add some Simplified Chinese translation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by kid0809** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **steveodonovan** You can assign the PR to them by writing `/assign @steveodonovan` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=tektoncd%2Fdashboard).
> 
> Needs approval from an approver in each of these files:
> * **[OWNERS](https://github.com/tektoncd/dashboard/blob/main/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

/assign @steveodonovan

**Comment by AlanGreene** [comment]
Thanks for the PR @kid0809 
/ok-to-test

**Review by AlanGreene — APPROVED** [review]
/lgtm
/meow

**Pull request merged**
