### PR TITLE
Remove unused code from pipeline endpoint

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by eddycharly** [comment]
/test pull-tekton-dashboard-integration-0-13-2-tests

postman ?

**Comment by eddycharly** [comment]
newmann 5.1.2 was published 20 minutes ago...

**Comment by AlanGreene** [comment]
yeah looks like we hit a temporary issue with the npm registry not returning the postman-runtime package correctly (that version was published 5 hours ago). I've seen delays before, but they're normally < 10 minutes.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for postman-runtime@7.26.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'newman'
npm ERR! notarget 
```

All good now, but we should still pin the version anyway to avoid future issues.

**Pull request merged**
