### PR TITLE
Add term.tsv for Japanese translation and modify messages_ja.json

### PR DESCRIPTION
**Pull request by Martsings**
# Changes

We add `term.tsv` as a reference for Japanese translation and modify some mistakes in `messages_ja.json`.

`term.tsv` is a standard format of glossary, which can be used as a dictionary manually or be imported into some translation tools to improve the accuracy of translation. Every time after we have done some new translation, we will add new words we found into it so that it can be updated to be well used by other people.

PS: The recommended tool we are currently using is called [みんなの自動翻訳](https://mt-auto-minhon-mlt.ucri.jgn-x.jp/).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Thanks for the PR @Martsings. Can you please update the commit message with more information about the `.tsv` file? Is this a standard format? How is it expected to be used / updated? Is there particular tooling recommended? etc.

**Comment by Martsings** [comment]
@AlanGreene Thanks for your reply. I updated the message to give a introduction about `term.tsv` file. If more information about it is expected, please let me know.

**Comment by AlanGreene** [comment]
A readme makes sense, thanks 👍 Some basic information in the commit message would be useful too, similar to what you've put in the PR description.

**Comment by Martsings** [comment]
@AlanGreene We add `README.md` as a instruction for Japanese translation and modify the commit message to give a brief introduction for `term.tsv`. If there's any other requirement, please let me know.

**Review by AlanGreene — APPROVED** [review]
Thanks for the update, this looks good now.
/ok-to-test

**Pull request merged**
