### PR TITLE
Update to Carbon 10.11

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1133

Update to:
- carbon-components@10.11
- carbon-components-react@7.11

This brings a number of accessibility improvements, as well
as a fix for the combobox issue that prevented users from
typing in the namespaces dropdown.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Thanks to @CarolynMabbott for catching a change in behaviour for the LabelFilter component due to the Carbon update. Fix included here.

**Comment by Megan-Wright** [comment]
@AlanGreene been testing this one out with Carolyn this morning - not seeing anything at all wrong with it, however, we noticed that the `x` on filter labels are a very dark colour and not at all obvious that they are there considering how small they are (pretty sure they used to be white):
Screenshot 2020-05-18 at 11 04 22
What are your thoughts on this? thanks

**Comment by AlanGreene** [comment]
@Megan-Wright thanks for catching that, looks like the latest patch release introduced some unexpected changes to the Tag component. There'll be more changes in 10.12 to support a new 'high-contrast' Tag type so we'll be able to remove our custom styles.

Should be good now:
image

**Comment by AlanGreene** [comment]
@a-roberts did a `git commit --amend` to give the EasyCLA check a much-needed kick...

**Pull request merged**
