### PR TITLE
Remove details of CEL-interceptors from EventListener display

### PR DESCRIPTION
**Pull request by Megan-Wright**
# Changes
For: https://github.com/tektoncd/dashboard/issues/1129
- Removes the display of CEL-interceptor details due to potential security issues
- Removes the YAML view for EventListeners to avoid displaying sensitive details
- Updates tests to account for these details not being displayed 
- Also removes the `interceptorName` variable as nowhere is actually using it anymore

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by Megan-Wright** [comment]
@a-roberts Example EventListener with CEL-interceptor
```apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            filter: "header.match('X-GitHub-Event', 'push')"
      bindings:
      - name: pipeline-binding
      template:
        name: pipeline-template

**Comment by AlanGreene** [comment]
/lgtm

should be simple enough to restore the previous functionality onces triggers supports secure referencing of sensitive values

**Comment by a-roberts** [comment]
/test tekton-dashboard-unit-tests

Yeah this flaky is a real problem

**Pull request merged**
