### PR TITLE
[WIP] Limit visibility to single namespace

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR implements single namespace visibility in the tekton dashboard (see https://github.com/tektoncd/dashboard/issues/1018)

/cc @a-roberts @AlanGreene 

Changes are detailed below:

## Backend

RBAC is split into multiple `Role`/`ClusterRole` according to the concern they address.

| Concern | Tenancy mode | Resource type | Binding type | Scope |
| --- | --- | --- | --- | --- |
| Lookup pipelines infos | NA | `ClusterRole` | `RoleBinding` | namespace `tekton-pipelines` |
| Lookup triggers infos | NA | `ClusterRole` | `RoleBinding` | namespace `tekton-pipelines` |
| Backend | NA | `ClusterRole` | `ClusterRoleBinding` | cluster |
| Aggregate | NA | `ClusterRole` | `ClusterRoleBinding` | cluster |
| Tenant | single namespace | `ClusterRole` | `RoleBinding` | namespace `tekton-tenant` |
| Tenant | whole cluster | `ClusterRole` | `ClusterRoleBinding` | cluster |

A few more details:
- keep in mind that `ClusterRole` doesn't mean permissions at the cluster level, it depends on the type of binding (`RoleBinding` means namespace level permissions, `ClusterRoleBinding` means cluster level permissions)

- backend `ClusterRole` is the necessary permissions for the backend to work, it doesn't cover permissions related to tekton pipelines or triggers resources, only those related to the backend internals (dashboard extensions essentially). It also covers cluster wide tekton resources (`clustertasks` and `clustertriggerbindings`) as they are cluster wide by nature.

- aggregate `ClusterRole` is cluster wide. This is used by extensions and as extensions are not very mature yet this could change as things go

The properties endpoint now has a `TenantNamespace` property set to `tekton-tenant` when single namespace tenancy is set.

Additionally, controllers are run against the tenant namespace and only see changes occuring in this namespace so that changes in another namespace are not broadcasted.

## Frontend

On the frontend side, when retrieving the properties from the backend, if `TenantNamespace` is set
- we use this namespace to populate namespace selection drop downs.
- the `All namespaces` item in the drop down is not shown
- we call the `selectNamespace` action to make the `tekton-tenant` namespace the active selection
- all api calls performed to the backend are consequently related to the `tekton-tenant` namespace
- api calls to the backend requesting cluster level permissions will most likely fail and should not be performed

## Kustomize

Two variations of the kustomize bases are available:
- `/base/rbac-cluster` for the whole cluster visibility
- `/base/rbac-namespace` for the single namespace visibility

An overlay `/ovelays/dev-single-namespace` was added to deploy the single namespace visibility dashboard version.

## Tests

End to end tests used the `tekton-dashboard` service account, that led to a service account having more permissions than necessary.
I changed that to make the end to end tests execute pipeline runs with a separate service account so that unnecessary permissions could be removed from the stock dashboard service account.

Fontend tests were adapted to work with the default cluster visibility, there are no single namespace visibility tests yet.

## Todos

- single namespace visibility frontend tests
- should we completely hide the drop down in the side nav when single namespace visibility is on ?
- more overlays
- manual testing

## Notes

The implementation uses command line arguments instead of env variables. Reasoning behind this is detailed here https://github.com/tektoncd/dashboard/pull/1364.
I can revert to env variables if necessary but I would prefer to switch to go flags for the reasons explained in the linked PR.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by eddycharly** [comment]
@a-roberts as you seem to know OpenShift well, is it ok if i move the OpenShift related RBAC from the base to the overlays ?
Will it be an issue when making a release ?

**Comment by eddycharly** [comment]
Arf, tests are failing because of trying to use the dashboard service account for pipeline runs that need to create a `Service`.
Not a good idea to add these permissions to the dashboard service account as it doesn't need them.
I will have to change the e2e tests to create and use a separate service account.

**Comment by eddycharly** [comment]
Green !! 🎉 

I updated the PR description, this is not finished yet but it's getting close, review/feedback on the approach taken welcome.
Maybe i can show a demo in next workgroup meeting ?

**Comment by a-roberts** [comment]
> @a-roberts as you seem to know OpenShift well, is it ok if i move the OpenShift related RBAC from the base to the overlays ?
> Will it be an issue when making a release ?

Hey, only just seeing this - hmm, I can give the release run a try, I think you'd be able to if you either remove references to the release secret or make a dummy one

I see there are substantial solid changes here so a demo at your convenience would be super

**Comment by eddycharly** [comment]
I will join the WG meeting this afternoon.
I can do a little demo if it's ok.

**Comment by a-roberts** [comment]
Discussed on the working group call today after the demo, so my notes are as follows

1. Disabling or not showing the dropdown on the left when there's just the one visible namespace anyway (@AlanGreene had a suggestion for how best to do it)

2. Installation: currently this will double the number of release assets required AIAU (single-namepace versus all, due to the use of ClusterRoleBindings vs RoleBindings) - any ways around this? Helm charts (or just using templating from a dry run then applying for those not wanting a Tiller)?

3. OpenShift implications if any: (needs testing, presumably the Route would just sit in the tenant namespace?)

**Comment by eddycharly** [comment]
> Installation: currently this will double the number of release assets required AIAU (single-namepace versus all, due to the use of ClusterRoleBindings vs RoleBindings) - any ways around this? Helm charts (or just using templating from a dry run then applying for those not wanting a Tiller)?

Kustomize is somewhat limited but it does the job, I would keep kustomize for now and discuss other options in another issue.

> OpenShift implications if any: (needs testing, presumably the Route would just sit in the tenant namespace?)

Can the Route be in another namespace than the service ?

**Comment by eddycharly** [comment]
I am working on kustomize, trying to get something easy to use, maintain and test.

I would like to have all combinations in a hierarchy, something like `/overlays/dev/k8s/single-namespace/read-only`.

I will see what i can come up with and maybe we can discuss the solution.

Also, as this PR is getting pretty big, i would like to split it into smaller PRs and merge gradually.

**Comment by a-roberts** [comment]
> I am working on kustomize, trying to get something easy to use, maintain and test.
> 
> I would like to have all combinations in a hierarchy, something like `/overlays/dev/k8s/single-namespace/read-only`.
> 
> I will see what i can come up with and maybe we can discuss the solution.
> 
> Also, as this PR is getting pretty big, i would like to split it into smaller PRs and merge gradually.

Yeah, sounds like a good plan.

Regarding Routes accessing a Service in a different namespace - I believe so but that won't change the implementation here (you could reference the Service via its DNS name, so like servicename.namespace.svc.cluster.local - not something I've tried personally).

I think it'd be useful to include an example topology with many Dashboard instances set up - suited to README.md under a new section. We could do this in a later PR once all the pieces are in place if you'd prefer.

**Comment by eddycharly** [comment]
> I think it'd be useful to include an example topology with many Dashboard instances set up - suited to README.md under a new section. We could do this in a later PR once all the pieces are in place if you'd prefer.

I thought about that too, but we're not quite there yet. It could be done relatively easily with helm but with bare kustomize it will be difficult as some resources need to be deployed only once (CRDs for example).

IMO this PR should just focus on single namespace visibility, not multiple deployments (easier to treat them as separate concerns i guess).

I will start splitting the PRs, there's the flags one already, i will open another one to use a separate account in e2e tests (to remove the unnecessary permissions on the root ClusterRole).

**Comment by a-roberts** [comment]
> > I think it'd be useful to include an example topology with many Dashboard instances set up - suited to README.md under a new section. We could do this in a later PR once all the pieces are in place if you'd prefer.
> 
> I thought about that too, but we're not quite there yet. It could be done relatively easily with helm but with bare kustomize it will be difficult as some resources need to be deployed only once (CRDs for example).
> 
> IMO this PR should just focus on single namespace visibility, not multiple deployments (easier to treat them as separate concerns i guess).
> 
> I will start splitting the PRs, there's the flags one already, i will open another one to use a separate account in e2e tests (to remove the unnecessary permissions on the root ClusterRole).

Cool, sounds good. I'll see if I can get round to testing the flags PR out today on my Docker Desktop and OpenShift clusters

**Comment by eddycharly** [comment]
The PR for flags has been merged, I started splitting this giant PR into smaller ones:
- Use separate service account in e2e test (https://github.com/tektoncd/dashboard/pull/1396)
- Add pipelines and triggers namespace flags (https://github.com/tektoncd/dashboard/pull/1398)

Next, i will start splitting RBAC resources (Roles, ClusterRoles, RoleBindings and ClusterRoleBindings) outside of single namespace visibility work, and i will try to restructure the kustomize overlays to get something easier to maintain.

I would also like to get more end 2 end tests, right now it is testing only one overlay, it would be nice to test more variations.

**Comment by eddycharly** [comment]
Next PRs:
- Separate RBAC used to lookup triggers and pipelines versions (https://github.com/tektoncd/dashboard/pull/1406)
- Add more variations in e2e tests (https://github.com/tektoncd/dashboard/pull/1400)

I will probably begin to add tenant namespace in the backend, keeping kustomize refactoring for later.

**Comment by eddycharly** [comment]
Backend support for single namespace visibility https://github.com/tektoncd/dashboard/pull/1411

**Comment by eddycharly** [comment]
Backend support should be coming soon.

Next one, very wip:
- Frontend support for single namespace visibility (https://github.com/tektoncd/dashboard/pull/1425)

**Comment by AlanGreene** [comment]
@eddycharly I'm closing this since you've already split it into smaller PRs, many of which have been merged or are currently under review.

**Pull request closed without merging**
