### PR TITLE
Ensure columns on About page are aligned across tables

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Fixes https://github.com/tektoncd/dashboard/issues/1495

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by Megan-Wright** [comment]
@AlanGreene thank you! This looks good and definitely fixes the problem, however I'm noticing that the tables are now only half the width of the page, which seems inconsistent with the rest of the dashboard... what are your thoughts on this?
Screenshot 2020-06-10 at 10 05 27

**Comment by AlanGreene** [comment]
Yeah this was intentional as the About tables are so sparse it felt weird having them stretch so wide. I'd like to add a Tekton cat or whatever the Dashboard logo ends up being on the right hand side to give the page a little character / colour.

**Comment by Megan-Wright** [comment]
Yep fair enough, that makes sense - all looks good then :)

**Comment by CarolynMabbott** [comment]
Have to say the idea of the Tekton cat on the right hand side sounds awesome 
Could we use the colourful cat from the website until we come up with a dashboard cat?

**Pull request merged**
