### PR TITLE
issue #1088 : add oauth proxy config option to skip the openshift sign-in pop-up window

### LINKED ISSUE #1088: update oauth-proxy config to skip sign-in pop-up window
background - 

Tekton UI is protected by OpenShift OAuth server via OAuth proxy,  Current configuration always display the sign-in page "Log in with Open Shift" before reaching OAuth login page. Since "login with OAuth" is the only option, we should skip this pop-up window, and go directly to OAuth login page.  Skipping the sign-in page is useful for SSO, if OpenShift OAuth server is configured to use one SSO server (like IBM ID, or google), user could access the UI securely and silently without clicking the button.

Jim and Chunlong have investigated and tested various SSO scenarios for platform applications, and believe that we should get rid of this unnecessary button (to avoid the click). 

To skip the button,  add the following property in oauth proxy configuration. 
skip-provider-button=true  (will skip sign-in-page to directly reach the next step: oauth/start)

### PR DESCRIPTION
**Pull request by arunavemulapalli**
fixes #1088
@googlebot I signed it!

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
@googlebot I signed it!

**Comment by a-roberts** [comment]
Contacted @arunavemulapalli over Slack and linked to the IBM process for getting the CLA handled

**Comment by arunavemulapalli** [comment]
@a-roberts - can you please review this change? I think that is the only action left for this pr before it can be merged.
Thanks.

**Comment by a-roberts** [comment]
> @a-roberts - can you please review this change? I think that is the only action left for this pr before it can be merged.
> Thanks.

Yep, change was always good - thanks for sticking with the CLA process

/lgtm
/approve

**Pull request merged**
