### PR TITLE
Add setting to enable log timestamps

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

~~Depends on https://github.com/tektoncd/dashboard/pull/2146~~
Closes https://github.com/tektoncd/dashboard/issues/2145

Add a toggle to the Settings page to allow users to display timestamps
on the step container logs. This produces a timestamp prefix on each
line in the same way as `kubectl logs <pod> --timestamps` and uses
the functionality provided by the Kubernetes API server.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by briangleeson — APPROVED** [review]
/lgtm

**Comment by AlanGreene** [comment]
@briangleeson rebased to resolve merge conflict

**Review by briangleeson — APPROVED** [review]
/lgtm

**Comment by qaifshaikh** [comment]
Is this working? Can someone confirm what versions this actually works on?
we still don't see timestamps on the logs even when enabled on the dashboard 🤔 
Can someone share a working screenshot?
cc @AlanGreene  🙏🏻

**Comment by AlanGreene** [comment]
This was introduced in Dashboard v0.19.0 and is working as expected.

Here's an example with it disabled:

image

Enable it in the settings:
image

View the same logs, now with timestamps:
image

You can test it for yourself at https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/9887b780-53c4-check-pr-has-kind-label-logs-stop?pipelineTask=create-data&step=write-data
(logs currently available but pod may be pruned soon)

**Comment by qaifshaikh** [comment]
Great! Can confirm, it works on `v0.26.0` and above. Thanks @AlanGreene

**Pull request merged**
