### PR TITLE
Update release Tasks and Pipeline to v1beta1

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1246

Update params + resources to conform to new structure for v1beta1

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
@a-roberts any thoughts on the best way to test this?

**Comment by a-roberts** [comment]
> @a-roberts any thoughts on the best way to test this?

Yeah I've been thinking about this, I'm wondering if https://github.com/tektoncd/catalog is the best option as it's now version tagged (e.g beta vs not)

**Comment by AlanGreene** [comment]
Not sure I follow... 

As far as I can tell everything _looks_ good. I've run it locally with the output steps disabled and the logs are good. Short of setting up a test GCS bucket I'm not sure how else to test this before we merge it and get it updated on dogfooding.

**Comment by a-roberts** [comment]
> Not sure I follow...
> 
> As far as I can tell everything _looks_ good. I've run it locally with the output steps disabled and the logs are good. Short of setting up a test GCS bucket I'm not sure how else to test this before we merge it and get it updated on dogfooding.

My bad, i answered a question you didn't actually ask, for https://github.com/tektoncd/dashboard/issues/1264 😆 

For this one, excellent! I can give this a good test on GCS then with my secret

**Comment by AlanGreene** [comment]
Thanks, give me a shout if you want to split testing on the other one or anything

**Comment by a-roberts** [comment]
Testing this one now 👀

**Comment by a-roberts** [comment]
I've been trying this, this morning, and seeing:

```
e/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:15.165061    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:16.170871    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:17.179403    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:18.196127    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:19.198952    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: EOF
E0409 11:33:30.201229    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: Get https://kubernetes.docker.internal:6443/apis/tekton.dev/v1alpha1/namespaces/default/pipelineruns?fieldSelector=metadata.name%3Ddashboard-release-run-pqqxl&includeUninitialized=true&limit=500&resourceVersion=0: net/http: TLS handshake timeout
E0409 11:33:36.199262    9796 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: the server could not find the requested resource (get pipelineruns.tekton.dev)
```

I'll give it another go now over lunch

**Comment by a-roberts** [comment]
```
[build : build-static] + npm run build_ko
[build : build-static] 
[build : build-static] > @tektoncd/dashboard@0.1.0 build_ko /workspace/go/src/github.com/tektoncd/dashboard
[build : build-static] > webpack --config webpack.prod.js --output-path='./cmd/dashboard/kodata/web' 
[build : build-static] 
[build : build-static] Killed
[build : build-static] npm ERR! code ELIFECYCLE
[build : build-static] npm ERR! errno 137
[build : build-static] npm ERR! @tektoncd/dashboard@0.1.0 build_ko: `webpack --config webpack.prod.js --output-path='./cmd/dashboard/kodata/web' `
[build : build-static] npm ERR! Exit status 137
[build : build-static] npm ERR! 
[build : build-static] npm ERR! Failed at the @tektoncd/dashboard@0.1.0 build_ko script.
[build : build-static] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build : build-static] 
[build : build-static] npm ERR! A complete log of this run can be found in:
[build : build-static] npm ERR!     /tekton/home/.npm/_logs/2020-04-09T10_54_33_991Z-debug.log

[build : copy-files-to-output-resource] 2020/04/09 10:54:34 Skipping step because a previous step failed

[build : source-mkdir-tekton-dashboard-git-bkv7t] 2020/04/09 10:54:34 Skipping step because a previous step failed

[build : source-copy-tekton-dashboard-git-q8r2n] 2020/04/09 10:54:35 Skipping step because a previous step failed
```

this time around

**Comment by AlanGreene** [comment]
137 = out of memory...

**Comment by a-roberts** [comment]
Giving this another go now, let's see if the OoM problem goes away

**Comment by a-roberts** [comment]
Yep, still seeing the 137 issue...

**Comment by a-roberts** [comment]
Looking into tackling the 137 problem now, seeing if I can increase the amount of memory we get for the pod. https://github.com/tektoncd/pipeline/blob/7004968bbbec8de3b4e071d31944e20eba68afa3/docs/pipelineruns.md mentions LimitRanges https://github.com/tektoncd/pipeline/blob/7004968bbbec8de3b4e071d31944e20eba68afa3/examples/v1beta1/pipelineruns/no-ci/limitrange.yaml so increasing it could be our best bet

**Comment by a-roberts** [comment]
Here's the working release pipeline for me:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "2Gi"
    default:
      cpu: "700m"
      memory: "2Gi"
    defaultRequest:
      cpu: "110m"
      memory: "2Gi"
    type: Container
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dashboard-release
spec:
  params:
    - name: package
      description: package to release
      default: github.com/tektoncd/dashboard
    - name: imageRegistry
      default: gcr.io/tekton-releases
    - name: versionTag
      description: The X.Y.Z version that the artifacts should be tagged with
    - name: bucketName
      description: The name of the bucket to use
  resources:
    - name: dashboard-source-repo
      type: git
    - name: bucket-for-dashboard
      type: storage
    - name: builtDashboardImage
      type: image
  tasks:
    - name: build
      taskRef:
        name: build-tekton-dashboard
      resources:
        inputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
        outputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
    - name: publish-images
      runAfter: [build]
      taskRef:
        name: publish-tekton-dashboard
      params:
        - name: pathToProject
          value: $(params.package)
        - name: versionTag
          value: $(params.versionTag)
        - name: imageRegistry
          value: $(params.imageRegistry)
        - name: bucketName
          value: $(params.bucketName)
      resources:
        inputs:
          - name: dashboard-source-repo
            resource: dashboard-source-repo
            from: [build]
          - name: bucket-for-dashboard
            resource: bucket-for-dashboard
        outputs:
          - name: bucket-for-dashboard
            resource: bucket-for-dashboard
          - name: builtDashboardImage
            resource: builtDashboardImage

```

I had to expand my Docker Desktop memory amount from 2 GB to 13 GB for this, so I'm going to open an issue in the pipelines repo as clearly that footprint requirement enough is massive

@AlanGreene I suggest adding the above into the PipelineRun, adding a note in the tekton/readme.md file (it's often me doing the releases and I reset my cluster a lot, so it's easy to forget needing to up the memory amount!) and then let's get this in. I'll update the webhooks extension pipeline PR too, then we should be off v1alpha1 for good 👍

**Comment by a-roberts** [comment]
Had a successful run of this today so no qualms here, let's get this in, thanks @AlanGreene 
/lgtm
/approve

**Pull request merged**
