### PR TITLE
Update to latest Storybook release

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

The main benefits we'll notice are improved build performance
and bug fixes for the grid display.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
let's try this again now that Ziheng has been added to the `dashboard.collaborators` team 🤞 
/cc @ziheng

**Review by steveodonovan — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
