### PR TITLE
Update Dev docs

### PR DESCRIPTION
**Pull request by kobaji**
Fix the URL of kustomize

# Changes

Fix the URL of kustomize

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
  - Not required.
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
  - Not required.
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by kobaji** [comment]
[The organization I belong to](https://github.com/fujitsu-cdf) has been authorized under a signed CLA.
Do this my individual ccount need to be authorized too?

**Comment by AlanGreene** [comment]
Thank you for the change.

If you click on the link in the easycla comment above you should see an option to choose 'Corporate', then search for and select your organization to make sure your GitHub account is correctly linked to the existing CLA. You should **not** need to sign an additional individual CLA.

/ok-to-test

**Comment by kobaji** [comment]
Thank you very much for your kind help, @AlanGreene 
I am asking to the CLA Manager in my team. I will go ahead once I've been authorized.

Thank you again for your kindness!

**Comment by kobaji** [comment]
Hi @AlanGreene Thank you very much for your kind help.
I found the EasyCLA was outdated. Therefore I need to make a new CLA.

I didn't know that the Tekton project transitioned to a foundation-wide CLA.
And right now I understand Tekton is now authorized under the Continuous Delivery Foundation CLA, so their repos are checking to see who has signed the CDF CLA instead of the now outdated Tekton CLA.

It might take a several days to be authorized under the CDF CLA, therefore I might make you wait for me.

**Comment by AlanGreene** [comment]
@kobaji yes that's right, we switched to the CDF CLA in April this year. No problem at all, feel free to message me here or on the Tekton Slack when your CLA is ready 😸

**Comment by kobaji** [comment]
Thank you very much for your kind help @AlanGreene , I managed to conclude CDF CLA.

@mnuttall @CarolynMabbott 
I would be very happy if you kindly reviewed this PR.
Thank you.

**Review by AlanGreene — APPROVED** [review]
/lgtm
/meow

**Pull request merged**
