### PR TITLE
Namespace message edited to be more readable

### PR DESCRIPTION
**Pull request by CarolynMabbott**
# Changes

Namespace message now returns a formatted list of namespaces separated by commas 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

References issue - https://github.com/tektoncd/dashboard/issues/144

### CODE REVIEW

**Comment by mnuttall** [comment]
Hi @CarolynMabbott I've checked out your branch and the error
```
cluster_test.go:43: Number of namespaces: expected: 1, returned: 0
```
is a genuine cause of the build failure on your PR, caused by your changing the return type from k8s.io/api/core/v1/NamespaceList to a comma-separated string. @AlanGreene you've indicated that you're happy with this change - shouldn't there be an accompanying .js change somewhere if @CarolynMabbott is changing the return format? Or is that not what you expected? Please advise.

**Comment by AlanGreene** [comment]
@mnuttall from our call on Tuesday we agreed that the log should be removed. That should be the only change here, I'm not expecting any impact on the front end at all. I left the `/ok-to-test` comment to unblock the pipeline so that once the change is ready it's not blocked waiting for that step, not as an indication of approval.

**Comment by AlanGreene** [comment]
@CarolynMabbott can you squash your commits?

**Comment by mnuttall** [comment]
/lgtm cancel
@CarolynMabbott sorry, do please squash your commits.

**Pull request closed without merging**
