### PR TITLE
Remove obsolete/unused files

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR removes obsolete/unused files:
- `Dockerfile_test` (not used by CI and devs)
- `Dockerfile_race_test` (not used by CI and devs)
- `testdata/*` (obsolete)
- `install-dev.sh` (not working)

How about those files too ?
- `minishift-delete-dashboard.sh` (is it used ?)
- `minishift-install-dashboard.sh` (is it used ?)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
I've never used any of those shell scripts, and the tests run by the Dockerfile are already run in CI without it so this gets a 👍 from me.

**Comment by eddycharly** [comment]
@AlanGreene i added `testdata/*` and `Dockerfile` too.
I think `Dockerfile` is used for openshift image stream though.

**Comment by AlanGreene** [comment]
`testdata/web` can definitely be removed, it's left over from some of the very early work on the dashboard.

`testdata/ordering` is probably better served by some of the examples in the pipelines repo. It was used for a while when we were testing a number of issues related to ordering of steps + Tasks in the UI.

**Pull request merged**
