### PR TITLE
Namespace message too verbose 

### PR DESCRIPTION
**Pull request by CarolynMabbott**
Remove unnecessary debug messages in cluster.go

References issue - #144

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by CarolynMabbott** [comment]
I signed it!

**Comment by mnuttall** [comment]
Hi @CarolynMabbott please can you check that your CLA-associated account is the one that this PR comes from?

**Comment by CarolynMabbott** [comment]
@mnuttall This PR does come from the account with the CLA

**Comment by AlanGreene** [comment]
@CarolynMabbott the commit on this PR has a `@users.noreply.github.com` email as the commit author. Check your git client config (`git config user.email`) and ensure it's set to the correct email associated with the CLA.

**Comment by a-roberts** [comment]
@CarolynMabbott ^^ can you please take a look?

**Comment by AlanGreene** [comment]
/lgtm

@a-roberts I'll leave the approval to you if you're happy with it

**Comment by a-roberts** [comment]
Yep, this is fine, thanks @CarolynMabbott 😄 

/approve

**Pull request merged**
