### PR TITLE
Fix client mode

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1388

Fix the error handling code used to detect when the Dashboard
is running in client mode (via `kubectl proxy`). Remove the
unwanted `data` field so we can correctly process the response
and provide the expected default install properties.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by ziheng — APPROVED** [review]
LGTM

**Review by briangleeson — APPROVED** [review]
/lgtm

**Pull request merged**
