### PR TITLE
Add --openshift flag

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR adds `--openshift` flag so that we don't need to guess if we are running on openshift or not.

This is safer and simpler as we already have the info at install or manifest generation time.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by eddycharly** [comment]
Yeah, it will remove the errors in the logs when we try to find the `Route` when running on docker desktop.

**Comment by eddycharly** [comment]
@a-roberts the `approved` label is not added automatically anymore ?

**Comment by a-roberts** [comment]
Raised on Slack 👀 https://github.com/tektoncd/dashboard/pull/1597#issuecomment-655391065 same behaviour

**Comment by eddycharly** [comment]
`/approve` worked for https://github.com/tektoncd/dashboard/pull/1597 maybe it was just yesterday (maybe prow was not reachable)

**Pull request merged**
