### PR TITLE
Update LabelFilter component design

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/966

Move 'Create' buttons to the DataTable header and remove
`additionalButton` prop from LabelFilter.

Also remove style overrides and 'Filters:' label from the tags.

Before:
image

After:
image

There are more changes to come in a later PR, including the addition of a 'clear all' button for the filters.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by steveodonovan** [comment]
So just hit enter to add the label ? That type of search bar does tend to lend itself to typeahead more than this, seems a little less intuitive

**Comment by AlanGreene** [comment]
@kimholmes see feedback from Steve above

**Comment by kimholmes** [comment]
Thanks. Yes. We've discussed the type ahead feature. Please ignore the design in this mock. Just focus on the type ahead dropdown. A type ahead feature like this one, especially one that can categorize the search term was put on the backburner because of the additional labeling that would need to be done on the backend. But, yes, I agree. A type ahead would be optimal. It's a matter of prioritization of the dev work.
TektonFilter4

**Comment by AlanGreene** [comment]
So should we go ahead with the change in this PR (press enter to add filter) or restore the 'Add filter' button until we have the typeahead functionality?

**Comment by kimholmes** [comment]
The design calls for the removal of the "Add filter" button. I think that's an older pattern and users know to press enter now.

**Comment by AlanGreene** [comment]
@steveodonovan back to you, happy enough with ^^^?

**Pull request merged**
