### PR TITLE
Periodically refresh install properties

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR periodically refreshes install properties (every 60s).
This allows updating the frontend when something changes on the backend side.

It's a quick and easy way of detecting changes. Something more advanced like using the websocket would require more work and would probably involve watching deployments in potentially various namespaces.

What do you think ? It seems to me that something simple like this requires almost no change and is acceptable in this case.

Closes https://github.com/tektoncd/dashboard/issues/1276

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
We already have websocket events for extensions, and a change to the dashboard config (e.g. switching to readonly / tenant mode) would require a redeploy so we should already be handling this through the websocket disconnect/reconnect which triggers us to re-fetch the data.

So the only case that's not handled by this is detecting Triggers / Pipelines updates, which would require watching deployments.

Is my understanding correct?

**Comment by eddycharly** [comment]
That’s correct. Watching pipelines and triggers deployment is not easy though. They can be deployed in separate namespaces or not deployed at all, the namespace could not even exist.

And when you look at the code to find the version it’s definitely a mess. I feel like watching for this on the backend is not as easy as it looks like.

**Comment by AlanGreene** [comment]
I agree, definitely not as easy as it should be.

Since installing / uninstalling Triggers isn't going to happen very often, and updates of Triggers or Pipelines should be similarly infrequent, I wonder if we need this at all?

While it would be nice to always display the latest data, I'm not a huge fan of frequent polling for something that's going to change so rarely. Maybe we could reduce the frequency, but then at what point does it become easier for the user to just refresh the page rather than wait for the UI to update itself?

**Comment by eddycharly** [comment]
I agree, and i don't mind closing this PR if we don't want to support this use case (that's just two lines of code ;-)

I just think it's not worth the effort to do it backend side and notifying though the web socket, at least not with the current level of complexity implemented in the backend.

**Comment by eddycharly** [comment]
@AlanGreene any more thoughts ? Do you prefer that i close this PR ?

**Comment by AlanGreene** [comment]
Yes let's close this for now, thanks.

**Pull request closed without merging**
