### PR TITLE
Adapting namespace for openshift in the overlays. Fixes #1227

### LINKED ISSUE #1227: Change namespace for Openshift
# Expected behavior
Openshift 4.x uses the Pipelines Operator which installs everything in the namespace openshift-pipelines by default. 
Probably it's necessary to change the kustomized manifests to this namespace.

# Actual behavior
Manifests use the tekton-pipelines namespace.

# Steps to reproduce the problem

1. Try to install the dashboard.

# Environment
- Kubernetes Platform:
Openshift 4.3

- Tekton Pipelines version:
Openshift pipelines 0.10.x

- Tekton Dashboard version:
latest

### PR DESCRIPTION
**Pull request by paolocarta**
# Changes

Adapting namespace for openshift in the overlays.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
/ok-to-test

Yeah, we're OK to sit by default in the Tekton Pipelines installation namespace (we used to have to be separate because of our Webhooks Extension and use of Knative), so I think this makes sense

**Comment by a-roberts** [comment]
Ah,

```

I0402 13:27:32.005]   15:31     error    no new line character at the end of file  (new-line-at-end-of-file)
I0402 13:27:32.006] 
I0402 13:27:32.007] overlays/dev-openshift-locked-down/kustomization.yaml
I0402 13:27:32.008]   15:31     error    no new line character at the end of file  (new-line-at-end-of-file)
I0402 13:27:32.008] 
I0402 13:27:32.009] overlays/dev-openshift/kustomization.yaml
I0402 13:27:32.010]   14:31     error    no new line character at the end of file  (new-line-at-end-of-file)
I0402 13:27:32.010] 
I0402 13:27:32.011] overlays/latest-openshift-locked-down/kustomization.yaml
I0402 13:27:32.012]   15:31     error    no new line character at the end of file  (new-line-at-end-of-file)
I0402 13:27:32.012] 
I0402 13:27:32.012] overlays/latest-openshift/kustomization.yaml
I0402 13:27:32.012]   14:31     error    no new line character at the end of file  (new-line-at-end-of-file)
```

spotted 👀

**Comment by a-roberts** [comment]
Thanks @paolocarta, almost there 😄 could you please squash your commits into one and then let's get it in? I prefer to use git rebase HEAD~4 for example and then pick `s` for each of the commits I want to be combined into one. We don't have the "squash and merge" option with the Prow set up here so otherwise you'd end up with all four commits instead of just the one tidy one, thanks

**Comment by paolocarta** [comment]
> Thanks @paolocarta, almost there 😄 could you please squash your commits into one and then let's get it in? I prefer to use git rebase HEAD~4 for example and then pick `s` for each of the commits I want to be combined into one. We don't have the "squash and merge" option with the Prow set up here so otherwise you'd end up with all four commits instead of just the one tidy one, thanks

Sure no problem!

**Pull request merged**
