### PR TITLE
Stop polling logs when run is terminated

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR stops polling logs when the run is terminated.

As we didn't react to state changes, polling was initiated but not stopped when run terminated.

/cc @a-roberts @AlanGreene 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
This was originally a deliberate choice as we couldn't guarantee all logs had been retrieved and displayed by the time the run terminated. @steveodonovan is this still required or is it safe to update now?

**Comment by AlanGreene** [comment]
Looks like this will be handled by #1578 when it's merged.

**Comment by eddycharly** [comment]
was handled by #1578
/close

**Pull request closed without merging**
