### PR TITLE
Fix rerun pipeline run

### LINKED ISSUE #1702: Rerunning a pipeline ignores taskRunSpecs
# Describe the bug

`PiepelineRuns` triggered through the Dashboard do not mirror the original `PipelineRun`'s `taskRunSpecs`.

If I had to guess, this is related to the fact that one can't specify `taskRunSpecs` when creating a `PipelineRun` through the Dashboard either.

# Expected behaviour

The pipeline run triggered via a rerun should have the same `taskRunSpecs` as the original one.

# Steps to reproduce the bug

1. Trigger a pipeline run with a task run spec
2. Click rerun on the dashboard

# Environment details

- Kubernetes Platform: Rancher

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner: AWS

- Versions:
   - Tekton Dashboard: v0.8.2
   
   - Tekton Pipelines: v0.15.1
   
   - Tekton Triggers: v0.7.0
   
- Install namespaces:
   - Tekton Dashboard: tekton-pipelines
   
   - Tekton Pipelines: tekton-pipelines
   
   - Tekton Triggers: tekton-pipelines
   

# Additional Info

```console
> kubectl get pr builders-pipeline-run-fxr5d -o yaml | grep taskServiceAccountName
    taskServiceAccountName: start-nginx-task

~~> exit code 0

> kubectl get pr builders-pipeline-run-fxr5d-r-dvgs4 -o yaml | grep taskServiceAccountName

~~> no output and exit code 1
```

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR fixes rerun pipeline run.

Closes #1702 

/cc @AlanGreene 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by AlanGreene — CHANGES_REQUESTED** [review]
The rerun PipelineRun is still missing `PipelineRun.spec.taskRunSpecs` with this change. Tested with https://github.com/tektoncd/pipeline/blob/be9ac3bf6b27f6beb3f4b7c828ef8388f9b323c3/examples/v1beta1/pipelineruns/no-ci/pipelinerun-taskrunspecs.yaml

I also noticed the `reruns` label is an empty string but I'm seeing that on the latest release too so it's unrelated to your change.

I think it makes sense to move the rerun API to the frontend code, there's no real need for this to be done on the backend and the client already has all the data it needs to create the new PipelineRun.

**Comment by eddycharly** [comment]
That's because the version of the pipeline package is old and doesn't know `PipelineRun.spec.taskRunSpecs`.

**Comment by eddycharly** [comment]
I updated the package, it should be good now.

**Review by AlanGreene — APPROVED** [review]
Confirmed it's working as expected now, thanks!

/lgtm
/meow

**Pull request merged**
