### PR TITLE
Move websocket to /resources. Add task and Pipeline Events to the web…

### PR DESCRIPTION
**Pull request by steveodonovan**
# Changes

Move websocket endpoint to /resources and add task and pipeline update events

https://github.com/tektoncd/dashboard/issues/237

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by steveodonovan** [comment]
Tests are passing locally and failing on prow. debugging here

**Comment by steveodonovan** [comment]
/assign @a-roberts @vtereso 

Could I get a review please ? Thanks

**Comment by a-roberts** [comment]
Excellent PR, /approve

Lemme know if you'd like this lgtmed immediately too or if there's any other work to be done!

**Comment by AlanGreene** [comment]
Confirmed with @steveodonovan this is ready to go :shipit: 

/lgtm
/approve

**Pull request merged**
