### PR TITLE
DataTable's Sort Function for Computed Values

### PR DESCRIPTION
**Pull request by carlos-logro**
issue: #817 

# Changes
By passing a custom sort function to the DataTable, the component is now able to sort strings, Links & Formatted Timestamps. 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

/cc @AlanGreene @a-roberts

### CODE REVIEW

**Comment by carlos-logro** [comment]
Unit test failing because global test coverage is below threshold.

**Comment by steveodonovan** [comment]
@carlos-logro FYI https://github.com/tektoncd/dashboard/issues/817#issuecomment-565459177 See my comment here. Paging will be an important piece here.I looked into it way back, it was far from trivial.

**Comment by carlos-logro** [comment]
> @carlos-logro FYI [#817 (comment)](https://github.com/tektoncd/dashboard/issues/817#issuecomment-565459177) See my comment here. Paging will be an important piece here.I looked into it way back, it was far from trivial.

what do you mean by paging?

**Comment by steveodonovan** [comment]
> what do you mean by paging?

`Pagination` If you're not familiar its limiting the result set to whats called a page with arrows to navigate through the `pages`. It's a very common pattern and we're going to need it. Otherwise too many resources for any given page will kill the UI. Sorting is something which needs to happen at the back end otherwise you pages are never going to be sorted.

@AlanGreene @a-roberts One of you might be more familiar with plans in this area but backend sorting and proper pagination is whats needed here. We could have 1000's of resources being loaded in this UI easily. The data has to be managed properly.

**Comment by a-roberts** [comment]
> > what do you mean by paging?
> 
> `Pagination` If you're not familiar its limiting the result set to whats called a page with arrows to navigate through the `pages`. It's a very common pattern and we're going to need it. Otherwise too many resources for any given page will kill the UI. Sorting is something which needs to happen at the back end otherwise you pages are never going to be sorted.
> 
> @AlanGreene @a-roberts One of you might be more familiar with plans in this area but backend sorting and proper pagination is whats needed here. We could have 1000's of resources being loaded in this UI easily. The data has to be managed properly.

So from our perspective in Hursley our priority is really around supporting our Triggers work with Kabanero and we haven't mentioned pagination in many months, I think the next juicy piece of UI work we're interested in is the showing of service accounts for secrets but there's a lot of other priorities too outside of UI work

Would it be reasonable to do this as a separate PR or do you think if one had, say, 1000 PipelineRuns in a namespace we'd simply be crippled on sort?

**Comment by carlos-logro** [comment]
but wouldn't the pagination part be done in the reducer or at mapStateToProps? The sorting that I added in this PR just overrides the one the DataTable component had as default. And the table only sorts items that were passed as rows so I'm assuming all the pagination logic is done way before passing those row items.

**Comment by steveodonovan** [comment]
lets discuss at the planning meeting later today

/hold

**Comment by a-roberts** [comment]
We've decided it's best to have a proper look into pagination and sorting before enabling this, so let's go ahead and make a new issue and then we can get this PR in once we're happy (otherwise users may experience dreadful performance we think and especially to do with the CSS animations)

**Comment by AlanGreene** [comment]
Closing this PR for now since there are other changes required before this can go in as discussed above.

**Pull request closed without merging**
