### PR TITLE
Update step container prefix

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/206

Remove 'build-' prefix from container name to match current
use in tektoncd/pipeline (0.5 has now been released with this change).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [-] ~~Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)~~
- [-] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
@AlanGreene is this a "breaking change" such that we won't work with previous pipeline versions? If so now would be an awesome time to state this in our readme: that you must be running 0.5 or later

**Comment by AlanGreene** [comment]
Yes, I had hoped the update to add the container name to the step status would make it into 0.5 so we could have handled this in a backwards compatible manner but unfortunately that didn't happen... I'll update the readme 👍

**Pull request merged**
