### PR TITLE
Update to go 1.22

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Update go to 1.22
Update other back-end build dependencies:
- ko 0.15
- kustomize 5.3
- golangci-lint 1.57

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by AlanGreene** [comment]
Expect at least some checks to fail until the test-runner image in the prow config is updated to `gcr.io/tekton-releases/dogfooding/test-runner:v20240322-4be9251150@sha256:622c058fe4d02053819a88faf1a0edaccf09920904c666712750b3fbeb987c80`

**Review by briangleeson — APPROVED** [review]
/lgtm

**Comment by AlanGreene** [comment]
Fix for latest failure: https://github.com/tektoncd/plumbing/pull/1898
Caused by a change introduced by Docker 25 which is included in the latest test-runner image.

**Comment by AlanGreene** [comment]
New image built, PR to bump Dashboard jobs to use it: https://github.com/tektoncd/plumbing/pull/1899

**Pull request merged**
