### PR TITLE
Remove PipelineResources

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Remove support for PipelineResources from the Dashboard. They have been deprecated
since Tekton Pipelines v0.30.0 in November 2021.

This also involves updating the Import Resources functionality to use a Task
instead of PipelineResources (git). The Task uses the git-init image also used
by the git-clone Task in the catalog.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (new features, significant UI changes, API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Remove PipelineResources support from the UI. This includes their list and details pages, the Resources tabs on the PipelineRun and TaskRun details pages, as well as the form-based Create PipelineRun and Create TaskRun pages. Update Import Resources to use a Task instead of PipelineResources for the git clone operation.
```

### CODE REVIEW

**Review by briangleeson — APPROVED** [review]
/lgtm

Looks good from scanning through 👍

**Comment by AlanGreene** [comment]
Hi @lj19950508, there are a number of options depending on your specific needs.

If you're using a Tekton Pipelines release which still supports PipelineResources you can use an older Tekton Dashboard release which still provides this functionality. Tekton Dashboard v0.30 LTS is the only supported version which still displays PipelineResources, and has been tested with Tekton Pipelines v0.38.x - v0.41.x. It will be end-of-life in October this year.

If you're using a recent Tekton Pipelines release which has removed support for PipelineResources there are different options depending on which PipelineResource types you were using. Most of the PipelineResource types have one or more Tasks in the Tekton Catalog that can be used as replacements. See the docs for some examples and additional guidance: https://tekton.dev/docs/pipelines/pipelineresources/

If you run into any problems feel free to join the [Tekton Slack workspace](https://github.com/tektoncd/community/blob/main/contact.md#slack) (for example the #dashboard or #pipeline channels) or open a discussion on GitHub. If your questions are related to the Tekton Pipelines API and features they're probably better suited to the [tektoncd/pipeline](https://github.com/tektoncd/pipeline) repo, or if they're related to the Dashboard's features you can use this repo.

**Comment by lj19950508** [comment]
i need  form-based Create PipelineRun and Create TaskRun pages

**Pull request merged**
