### PR TITLE
Add Conditions to the left nav

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1221

Add new SideNav item and corresponding routes for Conditions.

This uses the new ResourceDetails component for consistency,
the existing pages will be refactored to use this too in a
follow up PR.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Do we want to add additional content on the overview tab? It looks a bit bare at the moment:
image

I'm thinking:
- `description` (optional)
  - include it in the metadata block similar to how we include `ServiceAccount` for `EventListener`
- `params` (optional)
- `resources` (optional)
  - include these as tables below, same as on the Triggers resources

Not sure how to handle the `check` itself though since this is a `Step` and could take many forms. Displaying the raw YAML here doesn't make sense since it's available on the YAML tab.

**Comment by eddycharly** [comment]
/lgtm

Nothing to do on the backend ? Shouldn't we watch conditions ?

**Comment by AlanGreene** [comment]
Great catch. Looks like I didn't include my backend changes in https://github.com/tektoncd/dashboard/pull/1458. Not sure how that happened 😅 

I'll add them to this PR.

**Comment by AlanGreene** [comment]
Rebased to resolve merge conflict with messages_en.json, and fix unit tests after https://github.com/tektoncd/dashboard/pull/1467. Otherwise unchanged.

**Pull request merged**
