### PR TITLE
Add briangleeson as an approver

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Brian has made a number of great contributions to the Dashboard.
These include:
- fixes for Windows-based local development
- documentation updates
- providing great feedback and input to design and planning
- reviewing over 40 PRs including a series of significant changes
  affecting every single page of the application

His contributions to the project are greatly appreciated and we're
looking forward to his continued work with Tekton.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/dashboard/blob/main/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by briangleeson — APPROVED** [review]
/lgtm

😍

**Comment by AlanGreene** [comment]
EasyCLA not reporting, closing and reopening to fix that then I'll deal with the other checks not reporting correctly…

**Pull request merged**
